# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kvproto/rev_d4aeb46/replication_modepb.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='kvproto/rev_d4aeb46/replication_modepb.proto',
  package='kvproto.rev_d4aeb46.replication_modepb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n,kvproto/rev_d4aeb46/replication_modepb.proto\x12&kvproto.rev_d4aeb46.replication_modepb\"\xa4\x01\n\x11ReplicationStatus\x12\x45\n\x04mode\x18\x01 \x01(\x0e\x32\x37.kvproto.rev_d4aeb46.replication_modepb.ReplicationMode\x12H\n\x0c\x64r_auto_sync\x18\x02 \x01(\x0b\x32\x32.kvproto.rev_d4aeb46.replication_modepb.DRAutoSync\"\x99\x01\n\nDRAutoSync\x12\x11\n\tlabel_key\x18\x01 \x01(\t\x12\x46\n\x05state\x18\x02 \x01(\x0e\x32\x37.kvproto.rev_d4aeb46.replication_modepb.DRAutoSyncState\x12\x10\n\x08state_id\x18\x03 \x01(\x04\x12\x1e\n\x16wait_sync_timeout_hint\x18\x04 \x01(\x05\"z\n\x17RegionReplicationStatus\x12M\n\x05state\x18\x01 \x01(\x0e\x32>.kvproto.rev_d4aeb46.replication_modepb.RegionReplicationState\x12\x10\n\x08state_id\x18\x02 \x01(\x04*1\n\x0fReplicationMode\x12\x0c\n\x08MAJORITY\x10\x00\x12\x10\n\x0c\x44R_AUTO_SYNC\x10\x01*8\n\x0f\x44RAutoSyncState\x12\x08\n\x04SYNC\x10\x00\x12\t\n\x05\x41SYNC\x10\x01\x12\x10\n\x0cSYNC_RECOVER\x10\x02*T\n\x16RegionReplicationState\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x13\n\x0fSIMPLE_MAJORITY\x10\x01\x12\x18\n\x14INTEGRITY_OVER_LABEL\x10\x02\x62\x06proto3'
)

_REPLICATIONMODE = _descriptor.EnumDescriptor(
  name='ReplicationMode',
  full_name='kvproto.rev_d4aeb46.replication_modepb.ReplicationMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MAJORITY', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DR_AUTO_SYNC', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=535,
  serialized_end=584,
)
_sym_db.RegisterEnumDescriptor(_REPLICATIONMODE)

ReplicationMode = enum_type_wrapper.EnumTypeWrapper(_REPLICATIONMODE)
_DRAUTOSYNCSTATE = _descriptor.EnumDescriptor(
  name='DRAutoSyncState',
  full_name='kvproto.rev_d4aeb46.replication_modepb.DRAutoSyncState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SYNC', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ASYNC', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SYNC_RECOVER', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=586,
  serialized_end=642,
)
_sym_db.RegisterEnumDescriptor(_DRAUTOSYNCSTATE)

DRAutoSyncState = enum_type_wrapper.EnumTypeWrapper(_DRAUTOSYNCSTATE)
_REGIONREPLICATIONSTATE = _descriptor.EnumDescriptor(
  name='RegionReplicationState',
  full_name='kvproto.rev_d4aeb46.replication_modepb.RegionReplicationState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SIMPLE_MAJORITY', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTEGRITY_OVER_LABEL', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=644,
  serialized_end=728,
)
_sym_db.RegisterEnumDescriptor(_REGIONREPLICATIONSTATE)

RegionReplicationState = enum_type_wrapper.EnumTypeWrapper(_REGIONREPLICATIONSTATE)
MAJORITY = 0
DR_AUTO_SYNC = 1
SYNC = 0
ASYNC = 1
SYNC_RECOVER = 2
UNKNOWN = 0
SIMPLE_MAJORITY = 1
INTEGRITY_OVER_LABEL = 2



_REPLICATIONSTATUS = _descriptor.Descriptor(
  name='ReplicationStatus',
  full_name='kvproto.rev_d4aeb46.replication_modepb.ReplicationStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mode', full_name='kvproto.rev_d4aeb46.replication_modepb.ReplicationStatus.mode', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dr_auto_sync', full_name='kvproto.rev_d4aeb46.replication_modepb.ReplicationStatus.dr_auto_sync', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=253,
)


_DRAUTOSYNC = _descriptor.Descriptor(
  name='DRAutoSync',
  full_name='kvproto.rev_d4aeb46.replication_modepb.DRAutoSync',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='label_key', full_name='kvproto.rev_d4aeb46.replication_modepb.DRAutoSync.label_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='kvproto.rev_d4aeb46.replication_modepb.DRAutoSync.state', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state_id', full_name='kvproto.rev_d4aeb46.replication_modepb.DRAutoSync.state_id', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wait_sync_timeout_hint', full_name='kvproto.rev_d4aeb46.replication_modepb.DRAutoSync.wait_sync_timeout_hint', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=409,
)


_REGIONREPLICATIONSTATUS = _descriptor.Descriptor(
  name='RegionReplicationStatus',
  full_name='kvproto.rev_d4aeb46.replication_modepb.RegionReplicationStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='kvproto.rev_d4aeb46.replication_modepb.RegionReplicationStatus.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state_id', full_name='kvproto.rev_d4aeb46.replication_modepb.RegionReplicationStatus.state_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=411,
  serialized_end=533,
)

_REPLICATIONSTATUS.fields_by_name['mode'].enum_type = _REPLICATIONMODE
_REPLICATIONSTATUS.fields_by_name['dr_auto_sync'].message_type = _DRAUTOSYNC
_DRAUTOSYNC.fields_by_name['state'].enum_type = _DRAUTOSYNCSTATE
_REGIONREPLICATIONSTATUS.fields_by_name['state'].enum_type = _REGIONREPLICATIONSTATE
DESCRIPTOR.message_types_by_name['ReplicationStatus'] = _REPLICATIONSTATUS
DESCRIPTOR.message_types_by_name['DRAutoSync'] = _DRAUTOSYNC
DESCRIPTOR.message_types_by_name['RegionReplicationStatus'] = _REGIONREPLICATIONSTATUS
DESCRIPTOR.enum_types_by_name['ReplicationMode'] = _REPLICATIONMODE
DESCRIPTOR.enum_types_by_name['DRAutoSyncState'] = _DRAUTOSYNCSTATE
DESCRIPTOR.enum_types_by_name['RegionReplicationState'] = _REGIONREPLICATIONSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReplicationStatus = _reflection.GeneratedProtocolMessageType('ReplicationStatus', (_message.Message,), {
  'DESCRIPTOR' : _REPLICATIONSTATUS,
  '__module__' : 'kvproto.rev_d4aeb46.replication_modepb_pb2'
  # @@protoc_insertion_point(class_scope:kvproto.rev_d4aeb46.replication_modepb.ReplicationStatus)
  })
_sym_db.RegisterMessage(ReplicationStatus)

DRAutoSync = _reflection.GeneratedProtocolMessageType('DRAutoSync', (_message.Message,), {
  'DESCRIPTOR' : _DRAUTOSYNC,
  '__module__' : 'kvproto.rev_d4aeb46.replication_modepb_pb2'
  # @@protoc_insertion_point(class_scope:kvproto.rev_d4aeb46.replication_modepb.DRAutoSync)
  })
_sym_db.RegisterMessage(DRAutoSync)

RegionReplicationStatus = _reflection.GeneratedProtocolMessageType('RegionReplicationStatus', (_message.Message,), {
  'DESCRIPTOR' : _REGIONREPLICATIONSTATUS,
  '__module__' : 'kvproto.rev_d4aeb46.replication_modepb_pb2'
  # @@protoc_insertion_point(class_scope:kvproto.rev_d4aeb46.replication_modepb.RegionReplicationStatus)
  })
_sym_db.RegisterMessage(RegionReplicationStatus)


# @@protoc_insertion_point(module_scope)
